Repository BartWojtowicz/videopython, pull requests merged in 2023-11, with the labels that each got.

#10 Fix transition cutting wrong frames of 1st video.
  videopython/transitions.py
Labels: bug

#11 Fix Apache version.
  pyproject.toml
Labels: bug

#23 Add tests for VideoComposer.
  pyproject.toml
  src/videopython/base/compose.py
  src/videopython/base/transforms.py
  src/videopython/base/transitions.py
  tests/conftest.py
  tests/test_compose.py
  tests/test_transforms.py
  tests/test_transitions.py
  tests/test_video.py
Labels: enhancement, tests

#29 Creating video from image
  src/videopython/base/video.py
  tests/test_data/small_image.png
  tests/test_transforms.py
  tests/test_video.py
Labels: enhancement

#28 Generating static scene using stability.ai
  pyproject.toml
  requirements.txt
  src/videopython/project_config.py
  src/videopython/utils/stability_generation.py
  tests/test_compose.py
  tests/test_transforms.py
Labels: enhancement
